'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.1.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2", IsNullable:=false)>  _
Partial Public Class forestUsageReport
    
    Private serviceInfoField As serviceInfo
    
    Private headerField As forestUsageReportHeader
    
    Private woodHarvestingField() As woodHarvestingRow
    
    Private notWoodHarvestingField() As notWoodHarvestingRow
    
    Private measureField() As measureRow
    
    Private attachmentsField() As file
    
    '''<remarks/>
    Public Property serviceInfo() As serviceInfo
        Get
            Return Me.serviceInfoField
        End Get
        Set
            Me.serviceInfoField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property header() As forestUsageReportHeader
        Get
            Return Me.headerField
        End Get
        Set
            Me.headerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable:=false)>  _
    Public Property woodHarvesting() As woodHarvestingRow()
        Get
            Return Me.woodHarvestingField
        End Get
        Set
            Me.woodHarvestingField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable:=false)>  _
    Public Property notWoodHarvesting() As notWoodHarvestingRow()
        Get
            Return Me.notWoodHarvestingField
        End Get
        Set
            Me.notWoodHarvestingField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute("row", IsNullable:=false)>  _
    Public Property measure() As measureRow()
        Get
            Return Me.measureField
        End Get
        Set
            Me.measureField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
    Public Property attachments() As file()
        Get
            Return Me.attachmentsField
        End Get
        Set
            Me.attachmentsField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class serviceInfo
    
    Private providerField As String
    
    Private versionField As String
    
    Private nameField As serviceInfoName
    
    Private guidField As String
    
    Public Sub New()
        MyBase.New
        Me.versionField = "3.0"
        Me.guidField = "51a51362-192a-45c6-8947-33e97f420dbf"
    End Sub
    
    '''<remarks/>
    Public Property provider() As String
        Get
            Return Me.providerField
        End Get
        Set
            Me.providerField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property name() As serviceInfoName
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.ComponentModel.DefaultValueAttribute("51a51362-192a-45c6-8947-33e97f420dbf")>  _
    Public Property guid() As String
        Get
            Return Me.guidField
        End Get
        Set
            Me.guidField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Public Enum serviceInfoName
    
    '''<remarks/>
    forestDeclaration
    
    '''<remarks/>
    forestUsageReport
    
    '''<remarks/>
    forestFireSecurity
    
    '''<remarks/>
    forestProtection
    
    '''<remarks/>
    forestReproduction
    
    '''<remarks/>
    forestPathologyReport
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class file
    
    Private idField As String
    
    Private nameField As String
    
    Private extensionField As String
    
    Private signatureField() As Byte
    
    '''<remarks/>
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property extension() As String
        Get
            Return Me.extensionField
        End Get
        Set
            Me.extensionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")>  _
    Public Property signature() As Byte()
        Get
            Return Me.signatureField
        End Get
        Set
            Me.signatureField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2")>  _
Partial Public Class measureRow
    
    Private measureField As reference
    
    Private objectField As reference
    
    Private locationField As location
    
    Private areaField As Decimal
    
    Private farmField As farm
    
    Private farmFieldSpecified As Boolean
    
    Private formCuttingField As formCutting
    
    Private formCuttingFieldSpecified As Boolean
    
    Private typeCuttingField As reference
    
    Private woodField As reference
    
    Private sortimentField As reference
    
    Private valueField As Decimal
    
    Private valueFieldSpecified As Boolean
    
    Private commercialValueField As Decimal
    
    Private commercialValueFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property measure() As reference
        Get
            Return Me.measureField
        End Get
        Set
            Me.measureField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property [object]() As reference
        Get
            Return Me.objectField
        End Get
        Set
            Me.objectField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property location() As location
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property area() As Decimal
        Get
            Return Me.areaField
        End Get
        Set
            Me.areaField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property farm() As farm
        Get
            Return Me.farmField
        End Get
        Set
            Me.farmField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property farmSpecified() As Boolean
        Get
            Return Me.farmFieldSpecified
        End Get
        Set
            Me.farmFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property formCutting() As formCutting
        Get
            Return Me.formCuttingField
        End Get
        Set
            Me.formCuttingField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property formCuttingSpecified() As Boolean
        Get
            Return Me.formCuttingFieldSpecified
        End Get
        Set
            Me.formCuttingFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property typeCutting() As reference
        Get
            Return Me.typeCuttingField
        End Get
        Set
            Me.typeCuttingField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property wood() As reference
        Get
            Return Me.woodField
        End Get
        Set
            Me.woodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property sortiment() As reference
        Get
            Return Me.sortimentField
        End Get
        Set
            Me.sortimentField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property value() As Decimal
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property valueSpecified() As Boolean
        Get
            Return Me.valueFieldSpecified
        End Get
        Set
            Me.valueFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property commercialValue() As Decimal
        Get
            Return Me.commercialValueField
        End Get
        Set
            Me.commercialValueField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property commercialValueSpecified() As Boolean
        Get
            Return Me.commercialValueFieldSpecified
        End Get
        Set
            Me.commercialValueFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class reference
    
    Private idField As String
    
    Private nameField As String
    
    Private descriptionField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property description() As String
        Get
            Return Me.descriptionField
        End Get
        Set
            Me.descriptionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class location
    
    Private forestryField As reference
    
    Private subforestryField As reference
    
    Private tractField As reference
    
    Private quarterField As String
    
    Private taxationUnitField As String
    
    Private cuttingAreaField As String
    
    Public Sub New()
        MyBase.New
        Me.quarterField = "1"
        Me.taxationUnitField = "1"
    End Sub
    
    '''<remarks/>
    Public Property forestry() As reference
        Get
            Return Me.forestryField
        End Get
        Set
            Me.forestryField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property subforestry() As reference
        Get
            Return Me.subforestryField
        End Get
        Set
            Me.subforestryField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property tract() As reference
        Get
            Return Me.tractField
        End Get
        Set
            Me.tractField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property quarter() As String
        Get
            Return Me.quarterField
        End Get
        Set
            Me.quarterField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property taxationUnit() As String
        Get
            Return Me.taxationUnitField
        End Get
        Set
            Me.taxationUnitField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property cuttingArea() As String
        Get
            Return Me.cuttingAreaField
        End Get
        Set
            Me.cuttingAreaField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/sTypes/3.1")>  _
Public Enum farm
    
    '''<remarks/>
    Мягколиственное
    
    '''<remarks/>
    Твердолиственное
    
    '''<remarks/>
    Хвойное
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/sTypes/3.1")>  _
Public Enum formCutting
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Сплошная рубка")>  _
    Сплошнаярубка
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("Выборочная рубка")>  _
    Выборочнаярубка
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2")>  _
Partial Public Class notWoodHarvestingRow
    
    Private usageTypeField As reference
    
    Private locationField As location
    
    Private areaField As Decimal
    
    Private resourceTypeField As reference
    
    Private unitTypeField As reference
    
    Private volumeField As Decimal
    
    Private volumeFieldSpecified As Boolean
    
    '''<remarks/>
    Public Property usageType() As reference
        Get
            Return Me.usageTypeField
        End Get
        Set
            Me.usageTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property location() As location
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property area() As Decimal
        Get
            Return Me.areaField
        End Get
        Set
            Me.areaField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property resourceType() As reference
        Get
            Return Me.resourceTypeField
        End Get
        Set
            Me.resourceTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property unitType() As reference
        Get
            Return Me.unitTypeField
        End Get
        Set
            Me.unitTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property volume() As Decimal
        Get
            Return Me.volumeField
        End Get
        Set
            Me.volumeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property volumeSpecified() As Boolean
        Get
            Return Me.volumeFieldSpecified
        End Get
        Set
            Me.volumeFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2")>  _
Partial Public Class woodHarvestingRow
    
    Private locationField As location
    
    Private areaSquareField As Decimal
    
    Private areaCuttingField As Decimal
    
    Private farmField As farm
    
    Private formCuttingField As formCutting
    
    Private typeCuttingField As reference
    
    Private woodField As reference
    
    Private sortimentField As reference
    
    Private valueField As Decimal
    
    Private noteField As String
    
    Public Sub New()
        MyBase.New
        Me.areaSquareField = CType(0.0000,Decimal)
    End Sub
    
    '''<remarks/>
    Public Property location() As location
        Get
            Return Me.locationField
        End Get
        Set
            Me.locationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property areaSquare() As Decimal
        Get
            Return Me.areaSquareField
        End Get
        Set
            Me.areaSquareField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property areaCutting() As Decimal
        Get
            Return Me.areaCuttingField
        End Get
        Set
            Me.areaCuttingField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property farm() As farm
        Get
            Return Me.farmField
        End Get
        Set
            Me.farmField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property formCutting() As formCutting
        Get
            Return Me.formCuttingField
        End Get
        Set
            Me.formCuttingField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property typeCutting() As reference
        Get
            Return Me.typeCuttingField
        End Get
        Set
            Me.typeCuttingField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property wood() As reference
        Get
            Return Me.woodField
        End Get
        Set
            Me.woodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property sortiment() As reference
        Get
            Return Me.sortimentField
        End Get
        Set
            Me.sortimentField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property value() As Decimal
        Get
            Return Me.valueField
        End Get
        Set
            Me.valueField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property note() As String
        Get
            Return Me.noteField
        End Get
        Set
            Me.noteField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class employee
    
    Private first_nameField As String
    
    Private last_nameField As String
    
    Private patronimic_nameField As String
    
    Private postField As String
    
    Private basisAuthorityField As String
    
    Private phoneField As String
    
    '''<remarks/>
    Public Property first_name() As String
        Get
            Return Me.first_nameField
        End Get
        Set
            Me.first_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property last_name() As String
        Get
            Return Me.last_nameField
        End Get
        Set
            Me.last_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property patronimic_name() As String
        Get
            Return Me.patronimic_nameField
        End Get
        Set
            Me.patronimic_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property post() As String
        Get
            Return Me.postField
        End Get
        Set
            Me.postField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property basisAuthority() As String
        Get
            Return Me.basisAuthorityField
        End Get
        Set
            Me.basisAuthorityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property phone() As String
        Get
            Return Me.phoneField
        End Get
        Set
            Me.phoneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class signerData
    
    Private employeeField As employee
    
    Private dateField As Date
    
    Private organizationField As String
    
    Public Sub New()
        MyBase.New
        Me.dateField = New Date(636041376000000000)
    End Sub
    
    '''<remarks/>
    Public Property employee() As employee
        Get
            Return Me.employeeField
        End Get
        Set
            Me.employeeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Date), "2016-07-15")>  _
    Public Property [date]() As Date
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property organization() As String
        Get
            Return Me.organizationField
        End Get
        Set
            Me.organizationField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class contract
    
    Private typeField As String
    
    Private numberField As String
    
    Private dateField As Date
    
    Private usageTypeField() As reference
    
    Private registrationNumberField As String
    
    Private approvingProjectField As String
    
    Private approvingDateField As Date
    
    Private approvingDateFieldSpecified As Boolean
    
    Public Sub New()
        MyBase.New
        Me.numberField = "б/н"
        Me.dateField = New Date(636041376000000000)
    End Sub
    
    '''<remarks/>
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property number() As String
        Get
            Return Me.numberField
        End Get
        Set
            Me.numberField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property [date]() As Date
        Get
            Return Me.dateField
        End Get
        Set
            Me.dateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("usageType")>  _
    Public Property usageType() As reference()
        Get
            Return Me.usageTypeField
        End Get
        Set
            Me.usageTypeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property registrationNumber() As String
        Get
            Return Me.registrationNumberField
        End Get
        Set
            Me.registrationNumberField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property approvingProject() As String
        Get
            Return Me.approvingProjectField
        End Get
        Set
            Me.approvingProjectField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property approvingDate() As Date
        Get
            Return Me.approvingDateField
        End Get
        Set
            Me.approvingDateField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property approvingDateSpecified() As Boolean
        Get
            Return Me.approvingDateFieldSpecified
        End Get
        Set
            Me.approvingDateFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class period
    
    Private beginField As Date
    
    Private endField As Date
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property begin() As Date
        Get
            Return Me.beginField
        End Get
        Set
            Me.beginField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
    Public Property [end]() As Date
        Get
            Return Me.endField
        End Get
        Set
            Me.endField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class individualEntrepreneur
    
    Private first_nameField As String
    
    Private last_nameField As String
    
    Private patronimic_nameField As String
    
    Private identity_documentField As individualEntrepreneurIdentity_document
    
    Private ogrnField As String
    
    Private innField As String
    
    Public Sub New()
        MyBase.New
        Me.ogrnField = "1060256009835"
        Me.innField = "526317984689"
    End Sub
    
    '''<remarks/>
    Public Property first_name() As String
        Get
            Return Me.first_nameField
        End Get
        Set
            Me.first_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property last_name() As String
        Get
            Return Me.last_nameField
        End Get
        Set
            Me.last_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property patronimic_name() As String
        Get
            Return Me.patronimic_nameField
        End Get
        Set
            Me.patronimic_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property identity_document() As individualEntrepreneurIdentity_document
        Get
            Return Me.identity_documentField
        End Get
        Set
            Me.identity_documentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property ogrn() As String
        Get
            Return Me.ogrnField
        End Get
        Set
            Me.ogrnField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property inn() As String
        Get
            Return Me.innField
        End Get
        Set
            Me.innField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class individualEntrepreneurIdentity_document
    
    Private nameField As String
    
    Private seriesField As String
    
    Private numberField As String
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property series() As String
        Get
            Return Me.seriesField
        End Get
        Set
            Me.seriesField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property number() As String
        Get
            Return Me.numberField
        End Get
        Set
            Me.numberField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class physicalPerson
    
    Private first_nameField As String
    
    Private last_nameField As String
    
    Private patronimic_nameField As String
    
    Private identity_documentField As physicalPersonIdentity_document
    
    Private innField As String
    
    Public Sub New()
        MyBase.New
        Me.innField = "526317984689"
    End Sub
    
    '''<remarks/>
    Public Property first_name() As String
        Get
            Return Me.first_nameField
        End Get
        Set
            Me.first_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property last_name() As String
        Get
            Return Me.last_nameField
        End Get
        Set
            Me.last_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property patronimic_name() As String
        Get
            Return Me.patronimic_nameField
        End Get
        Set
            Me.patronimic_nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property identity_document() As physicalPersonIdentity_document
        Get
            Return Me.identity_documentField
        End Get
        Set
            Me.identity_documentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property inn() As String
        Get
            Return Me.innField
        End Get
        Set
            Me.innField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class physicalPersonIdentity_document
    
    Private nameField As String
    
    Private seriesField As String
    
    Private numberField As String
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property series() As String
        Get
            Return Me.seriesField
        End Get
        Set
            Me.seriesField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property number() As String
        Get
            Return Me.numberField
        End Get
        Set
            Me.numberField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class juridicalPerson
    
    Private nameField As String
    
    Private innField As String
    
    Private ogrnField As String
    
    Private addressField As String
    
    Public Sub New()
        MyBase.New
        Me.innField = "0256017902"
        Me.ogrnField = "1060256009835"
    End Sub
    
    '''<remarks/>
    Public Property name() As String
        Get
            Return Me.nameField
        End Get
        Set
            Me.nameField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property inn() As String
        Get
            Return Me.innField
        End Get
        Set
            Me.innField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
    Public Property ogrn() As String
        Get
            Return Me.ogrnField
        End Get
        Set
            Me.ogrnField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://rosleshoz.gov.ru/xmlns/cTypes/3.1")>  _
Partial Public Class partner
    
    Private itemField As Object
    
    Private phoneField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("individualEntrepreneur", GetType(individualEntrepreneur)),  _
     System.Xml.Serialization.XmlElementAttribute("juridicalPerson", GetType(juridicalPerson)),  _
     System.Xml.Serialization.XmlElementAttribute("physicalPerson", GetType(physicalPerson))>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property phone() As String
        Get
            Return Me.phoneField
        End Get
        Set
            Me.phoneField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://rosleshoz.gov.ru/xmlns/forestUsageReport/3.2")>  _
Partial Public Class forestUsageReportHeader
    
    Private executiveAuthorityField As reference
    
    Private forestryField As reference
    
    Private partnerField As partner
    
    Private periodField As period
    
    Private contractField As contract
    
    Private signerDataField As signerData
    
    '''<remarks/>
    Public Property executiveAuthority() As reference
        Get
            Return Me.executiveAuthorityField
        End Get
        Set
            Me.executiveAuthorityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property forestry() As reference
        Get
            Return Me.forestryField
        End Get
        Set
            Me.forestryField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property partner() As partner
        Get
            Return Me.partnerField
        End Get
        Set
            Me.partnerField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property period() As period
        Get
            Return Me.periodField
        End Get
        Set
            Me.periodField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property contract() As contract
        Get
            Return Me.contractField
        End Get
        Set
            Me.contractField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property signerData() As signerData
        Get
            Return Me.signerDataField
        End Get
        Set
            Me.signerDataField = value
        End Set
    End Property
End Class
